### ISSUE TITLE
SPIKE: Investigate if license_url can be a list

### ISSUE THREAD

**Issue by marcoesters** [anaconda-distribution/anaconda-linter#129] opened 2022-11-10 16:55 UTC
The linter breaks if `license_url` is a list. Investigate if this is legal according to conda-build and implement if so.

**Comment by schuylermartin45** [comment] 2023-11-08 16:00
Duplicate of: https://github.com/anaconda-distribution/anaconda-linter/issues/197
Closing.

**Closed by schuylermartin45** 2023-11-08 16:00 UTC
